# Generated by Django 2.1.4 on 2019-01-05 17:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190105_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount_percent',
            field=models.PositiveSmallIntegerField(default=20, validators=[django.core.validators.MaxValueValidator(75)]),
        ),
    ]
