# Generated by Django 2.1.4 on 2019-01-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190105_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='gluten_free',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='vegetarian',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='music_format',
            field=models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl')], default='CD', max_length=10),
            preserve_default=False,
        ),
    ]
