# Generated by Django 2.1.4 on 2019-01-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190116_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='music_format',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='gluten_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='vegetarian',
            field=models.BooleanField(default=False),
        ),
    ]
