# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-08 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='price',
            new_name='base_price',
        ),
    ]
