# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170330_2000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='size',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='music_format',
            field=models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl')], default='CD', max_length=3),
            preserve_default=False,
        ),
    ]
