# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-31 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170331_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='music_format',
            field=models.CharField(choices=[('CD', 'CD'), ('Vinyl', 'Vinyl')], max_length=10),
        ),
    ]
